- name: automatic
  color: "FFFFFF"
  description: Automatic action

- name: bugfix
  color: "B60205"
  description: Fix for a bug

- name: dependency
  color: "1D76DB"
  description: Update for a dependency

- name: documentation
  color: "006B75"
  description: Change in the documentation

- name: drift
  color: "5319E7"
  description: Drift detection

- name: feature
  color: "D93F0B"
  description: Adding a new feature

- name: rejected
  color: "000000"
  description: Idea rejected

- name: request
  color: "0E8A16"
  description: External request

- name: test
  color: "FBCA04"
  description: Temporary test only
