name: Check for updates

on:
  schedule:
    # Run every day at 5.00 AM UTC
    - cron: "0 5 * * *"

jobs:
  check:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Check for new TF and TG
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make update-versions

      # env.VERSION_TAG is set by 'Check for new TF and TG' step

      - name: Commit and push changes (conditional)
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dependency/${{ env.VERSION_TAG }}
          commit_message: "[AUTOMATIC] Bump for ${{ env.VERSION_TAG }}"

      - name: Create pull request
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Bump for ${{ env.VERSION_TAG }}
          assignee: ${{ github.actor }}
          label: automatic,dependency
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true
