name: Check for updates

on:
  schedule:
    # Run every day at 5.00 AM UTC
    - cron: "0 6 * * *"

jobs:
  check:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new tags
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make check

      - name: Commit and push changes (conditional)
        # env.VERSION_TAG is set by 'Check for new tags' step
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dependency/${{ env.VERSION_TAG }}
          commit_prefix: "[AUTOMATIC] Bump for ${{ env.VERSION_TAG }}."
