name: Build and push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile

      - name: Build and Push Docker image
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: make build-and-push
