name: On pull request

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: Dockerfile
