name: Build and push to Docker Hub

on:
  push:
    branches:
      - "**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: Dockerfile

      - name: Build and push Docker image
        if: github.actor == 'Krzysztof-Szyper-Epam' && github.ref == 'refs/heads/master'
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: make build-and-push

      - name: Create pull request
        if: github.actor == 'Krzysztof-Szyper-Epam' && github.ref != 'refs/heads/master'
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto-pull-request"
          pr_body: "*Automated pull request*"
          pr_title: "Auto: ${{ github.event.commits[0].message }}"
